### ISSUE TITLE
Worker link has incorrect target worker.

### ISSUE THREAD

**Issue by austinnichols101** [Hydrospheredata/mist-ui#96]
To reproduce:
- Start multiple instances of the same function
- Click into one of the jobs
- Note the Worker Name (<youranalytic><guid>)
- Click on the worker name 

The page you arrive on is not always the correct guid.

ALSO NOTE: The worker link does not appear like a regular http link.  It should have the same formatting as an html link to visual show it is a link.

**Comment by dos65** [comment]
Can't reproduce. Maybe you turned off spark ui using `spark.ui.enabled` ?

**Comment by dos65** [comment]
closed by #105
